Update calen

diff --git a/calen b/calen
--- a/calen
+++ b/calen
@@ -1,5 +1,3 @@
-#!/bin/bash
-
 main() {
     utility_selector
 }
@@ -13,137 +11,101 @@ utility_selector() {
                 False "Date/Time" \
                 False "Calendar" \
                 False "Delete" \
-                False "Operating System Type" \
-                False "Computer CPU Informaiton" \
-                False "Memory Information" \
-                False "Hard Disk Information" \
-                False "Mounted File System" \
                 --cancel-label="Exit" \
                 --ok-label="Open"
     )
 
     case $selected_utility in
     "Date/Time")
-        echo -n "Date/Time"
+        date_time
         ;;
     "Calendar")
         echo -n "Calendar"
         ;;
     "Delete")
-        delete_file
-        ;;
-    "Operating System Type")
-        os_type
-        ;;
-    "Computer CPU Informaiton")
-        cpu_information
-        ;;
-    "Memory Information")
-        memory_info
-        ;;
-    "Hard Disk Information")
-        hdd_info
-        ;;
-    "Mounted File System")
-        file_system_type
+        delete_menu
         ;;
     *)
         echo -n "None Selected"
-        break
         ;;
     esac
 }
 
+date_time(){
+    zenity --info \
+            --title="Date and Time" \
+            --text="TIME: $(date "+%T") DATE: $(date "+%d-%B-%Y")"
+}
 
-delete_file() {
-    FILE=$(zenity --file-selection --title="Select a File")
+delete_menu() {
+    directory_input=$(
+        zenity --entry \
+                --title="Directory Path" \
+                --text="Enter a directory name (Eg. Desktop):" \
+                --entry-text="Desktop"
+    );
 
     case $? in
     0)
-        echo "\"$FILE\" selected."
-        # TODO
-        # Prompt User: Confirm File Deletion
-        # Action: Delete File
-        # Ouput: Success Message
+        if [ "$directory_input" = "" ]; then
+            # in case input is empty do
+            file_to_delete=$(file_selector $pwd)
+            delete_file $file_to_delete
+
+        else
+            # in case input is not empty do
+            file_to_delete=$(file_selector $HOME\/$directory_input)
+            delete_file $file_to_delete
+
+        fi
         ;;
     1)
-        echo "No file selected."
-        ;;
-    -1)
-        echo "An unexpected error has occurred."
-        ;;
-    esac
-}
-
-os_type() {
-    os_information=$(cat /etc/os-release)
-
-    zenity --text-info \
-        --title="Operating System Type" \
-        --ok-label="Go Back" <<<$os_information
-        --width=400
-        --height=500
-
-    case $? in
-    0)
+        # if cancel button is triggered go back to main menu
         main
         ;;
     esac
 }
 
-cpu_information() {
-    cpu_specification=$(lscpu)
-
-    zenity --text-info \
-        --title="Computer CPU Information" \
-        --ok-label="Go Back" <<<$cpu_specification
-        --width=600
-        --height=800
+file_selector() {
+    directory=$1
+    FILE=`zenity --file-selection --filename="$directory/" --title="Select a File"`
 
     case $? in
-    0)
-        main
-        ;;
+        0)
+            echo "$FILE"
+            ;;
+        1)
+            echo "No file selected." # TODO : Prompt User Warning and Go Back to delete_file()
+            ;;
+        -1)
+            echo "An unexpected error has occurred." # TODO : Prompt User about the error and go back to main menu
+            ;;
     esac
 }
 
-memory_info() {
-    memory_data=$(cat /proc/meminfo)
+delete_file() {
+    initial_directory=$pwd
+    full_path=$1
+    file_location="${full_path%/*}/"
+    file_name=$(basename ${full_path})
 
-    zenity --text-info \
-        --title="Memory Information" \
-        --ok-label="Go Back" <<<$memory_data
-        --width=600
-        --height=800
-
-    case $? in
-    0)
-        main
-        ;;
+    # prompt user a warning and accepts a confirmation, bool value yes or no
+    zenity --question \
+            --title="Deleting File" \
+            --text="You are about to delete file at path: '$full_path'. \n\n Are you sure you wish to proceed?"
+case $? in
+        0)
+            # if user input is Yes
+            cd $file_location
+            rm $file_name
+            cd $initial_directory
+            ;;
+        1)
+            # if user input is No
+            echo false # TODO : case false return to file_selector
+            ;;
     esac
 }
-
-# hdd_info() {
-#     # TODO
-#     # Find a replacement which doesn't require sudo,
-#     # or prompt user to enter password to use the following sudo command
-#     # sudo hdparm -I /dev/sda
-# }
-
-file_system_type() {
-    mount_list=$(mount | grep "^/dev")
-
-    zenity --text-info \
-        --title="Mounted File System" \
-        --ok-label="Go Back" <<<$mount_list
-
-    case $? in
-    0)
-        main
-        ;;
-    esac
-}
-
 
 # call main function and pass all command line parameters using "$@" as a list
-main "$@"
+main "$@"
