Update Good

diff --git a/Good b/Good
--- a/Good
+++ b/Good
@@ -10,13 +10,20 @@ do
     --cancel-label="Go Back" \
    --filename="$1.txt"   # Displays text information dialog 
    
-   if [ $? -eq 1 ] #check if cancel label has been selected
-   then
-       break #if true exits the loop
+   # check if cancel label has been selected
+   if [ $? -eq 1 ] 
+   
+   then  
+   # if true exits the loop and return to the menu
+       break 
+       
    else
-       ADD_EVENT=$(zenity --entry --title="ADD an event"--text="Add an event on $Date" --title="NEW EVENT" --width=500 --height=300) #displays a text entry dialog  and user input is saved in variable ADD_EVENT
-       echo "$ADD_EVENT">>"$1.txt" #user input is appended in a file
-   fi
+   # displays a text entry dialog  and user input is saved in variable ADD_EVENT
+       ADD_EVENT=$(zenity --entry --title="ADD an event"--text="Add an event on $Date" --title="NEW EVENT" --width=500 --height=300) 
+       
+   # user input is appended in a file
+       echo "$ADD_EVENT">>"$1.txt" 
+   fi 
 done   
 }
 
@@ -24,19 +31,31 @@ done
 Calendar(){
 while true
 do
-    Date=$(zenity --calendar --text="select a date to add an event" --ok-label "Add event" --cancel-label "cancel" --width=600 --height=400 --title="SELECT A DATE" --date-format='%d.%m.%Y' ) # Displays the calendar dialog box and store the date chosen in variable $Date
+    # Displays the calendar dialog box and store the date chosen in variable $Date
+    Date=$(zenity --calendar --text="select a date to add an event" --ok-label "Add event" --cancel-label "cancel" --width=600 --height=400 --title="SELECT A DATE" --date-format='%d.%m.%Y' ) 
    
-   if [ $? -eq 1 ] #$? = was last command succesfull . Answer is 0 means 'yes ok-label has been selected'. Non-zero values means 'No cancel-label has been selected'
-   then 
-      break
-   fi       
-   FILENAME="$Date.txt" #The file is assigned to variable FILENAME
-   if [ -f "$FILENAME" ] # check if the file with thay specific date exists
+   # $? = was last command succesfull . Answer is 0 means 'yes ok-label has been selected'. Non-zero values means 'No cancel-label has been selected'
+   if [ $? -eq 1 ] 
+   
    then
-       reminder "$Date" #if true reminder of that specific date is called and performs what is in the function reminder 
+   # returns to the memu
+      break 
+   fi
+   #The file(representing the date chosen) is assigned to variable FILENAME
+   FILENAME="$Date.txt" 
+   
+   # check if a file with that specific 'date'(name of file) exists
+   if [ -f "$FILENAME" ] 
+   
+   then
+   # if true reminder of that specific date is called and performs what is in the function reminder 
+       reminder "$Date" 
    else
-       ADD_EVENT=$(zenity --entry --title="ADD AN EVENT" --text="Add an event on $Date" --width=500 --height=300) # if false it displays an entry box and    the user input is stored in variable ADD_EVENT
-       echo "$ADD_EVENT">>"$FILENAME" #The user input is stored in the file FILENAME="Date.txt" which is a specific date
+   # if false it displays an entry box and   the user input is stored in variable ADD_EVENT
+       ADD_EVENT=$(zenity --entry --title="ADD AN EVENT" --text="Add an event on $Date" --width=500 --height=300) 
+       
+   # The user input is stored(appended) in the file FILENAME="Date.txt" which represents a specific date    
+       echo "$ADD_EVENT">>"$FILENAME" 
        reminder "$Date"
    fi
 done
